/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {


    Ponto a = new Ponto(5, 6);
    Ponto b = new Ponto(7, 8);

    System.out.println(a);

        System.out.println(a.distancia(b));
    }
}
