/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {

    private HashMap<String, Aluno> bancoDeDados;

    public App(){
        this.bancoDeDados = new HashMap<>();
    }

    private int menu(){
        int opcao = 0;
        System.out.println(".: SIGAA :.");
        System.out.println("Bem vindo ao Sistema!\nInsira o numero correspondente à sua escolha");
        System.out.println("1 - Cadastrar");
        System.out.println("2 - Editar");
        System.out.println("3 - Excluir");
        System.out.println("4 - Listar dados de um alunos");
        System.out.println("5 - Listar todos os alunos");
        System.out.println("6 - Sair");
        Scanner teclado = new Scanner(System.in);
        opcao = teclado.nextInt();
        teclado.nextLine();
        return opcao;
    }

    private boolean cadastrar(){
        Scanner teclado = new Scanner(System.in);
        System.out.println("Insira o Nome");
        String nome = teclado.nextLine();

        String matricula;
        do {
            System.out.println("Insira a Matrícula");
            matricula = teclado.nextLine();
            if (this.bancoDeDados.containsKey(matricula)){
                System.out.println("Matricula já existente, tente novamente");
            }
        }while(this.bancoDeDados.containsKey(matricula));


        System.out.println("Insira o Cusro");
        String curso = teclado.nextLine();

        System.out.println("Insira o Telefone");
        String telefone = teclado.nextLine();

        System.out.println("Email");
        String email = teclado.nextLine();

        System.out.println("Insira a Data");
        String dataString = teclado.nextLine();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataString, formato);

        if (!this.bancoDeDados.containsKey(matricula)) {
            Aluno a = new Aluno(nome, matricula, curso, telefone, email, data);
            this.bancoDeDados.put(matricula,a);
            return true;
        }
        return false;
    }

    private String listarAluno(){
        Scanner teclado = new Scanner(System.in);
        String matricula;
        do{
            System.out.println("Insira a matricula do aluno a ser pesquisado");
            matricula = teclado.nextLine();
        } while (this.bancoDeDados.containsKey(matricula));
        return this.bancoDeDados.get(matricula).toString();
    }

    private boolean excluirAluno(){
        Scanner teclado = new Scanner(System.in);
        String matricula;
        do{
            System.out.println("Insira a matricula do aluno a ser excluido");
            matricula = teclado.nextLine();
        } while (this.bancoDeDados.containsKey(matricula));


    }
    private String listarTodos(){
        return bancoDeDados.toString();
    }
    public static void main(String[] args) {

        App app = new App();
        int opcao;
        do {
            opcao = app.menu();
            switch (opcao){
                case 1 -> {
                    if (!app.cadastrar()) {
                        System.out.println("Erro no cadastro");
                    } else {
                        System.out.println("Usuário Cadastrado");
                    }
                }
//                case 2 -> app.editar();
//                case 3 -> app.excluir();
                case 4 -> System.out.println(app.listarAluno());
                case 5 -> System.out.println(app.listarTodos());
                default -> System.out.println("Opção Inválida");
            }
        } while (opcao!=6);


    }
}
