/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import jdk.jshell.PersistentSnippet;

public class App {

    public static void main(String[] args) {

        Personagem hugo = new Aldeao(50, 1, 10, 2);
        System.out.println(hugo.mover());

        System.out.println(((Aldeao)hugo).coletar("madeira", 90));

        Cavaleiro henrique = new Cavaleiro(150,5,10,120,60);
        System.out.println(henrique.mover());
    }
}
