/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import org.checkerframework.checker.units.qual.C;

import java.sql.SQLOutput;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<Motor> deposito = new ArrayList<>(3);

        Carro a = new Carro("fusca", "Branco", new Motor(60, 1500));
        System.out.println(a);

        deposito.add(a.getMotor());

        a.setMotor(new Motor(110, 2000));

        deposito.add(a.getMotor());

        a = new Carro("Uno", "Vermelho", new Motor(40, 1000));
        System.out.println(a);

        deposito.add(a.getMotor());

        System.out.println(deposito.toString());
    }
}
