/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);

        Telefone tel1 = new Telefone("6485", 123, "modelo1", 500, new Dimensao(10, 10, 10) );
        Telefone tel2 = new SemFio("111", 315, "modelo2", 658, new Dimensao(35,51,32), 87, 98, 446);
        SemFio tel3 = (SemFio) tel2;


        System.out.println(tel1.imprimirDados());
        System.out.println(tel2.imprimirDados());
        System.out.println(tel3.imprimirDados());

        int f = (int) 2.5;
        System.out.println(f);



    }
}
