/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import org.checkerframework.checker.units.qual.C;

import java.util.HashMap;

public class App {

    public static void main(String[] args) {

        Caixa<Pessoa> c = new Caixa<>();
        HashMap<Pessoa, String> pessoas = new HashMap<>();

        String s = "ADS";

        Pessoa p = new Pessoa("HUGO");

        Pessoa nova = c.getConteudo();

    }
}
