/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.sql.SQLOutput;

public class App {

    public static void main(String[] args) {
        
    }
}
