/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Retangulo r = new Retangulo();

        System.out.println(r.getAltura());
        System.out.println(r.getLargura());

        System.out.println(r);

        r.setAltura(5);
        System.out.println(r);


    }

}
