/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

    Horario h = new Horario(12, 35, 45);

        System.out.println(h);

    }
}
