/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.sql.SQLOutput;

public class App {

public static void main(String[] args) {

    Data a = new Data(5,4,2024);

    System.out.println(a);

    Data b = new Data(31,1,2028);

    System.out.println(b);

    System.out.println(a.diferencaDatasEmDias(b));

    Data c = new Data();
    System.out.println(c);
    }
}
